source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FFGlobalAlertController_Example', :exclusive => true do
  pod "FFGlobalAlertController", :path => "../"
end

target 'FFGlobalAlertController_Tests', :exclusive => true do
  pod "FFGlobalAlertController", :path => "../"

  
end
